spring.application.name=hamrotrading

server.port=8848

#MySQL configuration
spring.datasource.url=jdbc:mysql://localhost:3306/trading_db
spring.datasource.username=root
spring.datasource.password=PrabinMysql
#JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
